files:
  - source: localeconstants1.properties
    translation: /%file_name%_%locale_with_underscore%.%file_extension%
  - source: /i18n/localeconstants2.properties
    translation: /%file_name%_%locale_with_underscore%.%file_extension%